name: Download Dropbox Files and Save Locally

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  download-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install Dependencies
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dropbox
       

    # Step 4: Download Files from Dropbox
    - name: Download Files from Dropbox
      env:
        DROPBOX_REFRESH_TOKEN : ${{ secrets.DROPBOX_REFRESH_TOKEN}}
        DROPBOX_APP_KEY : ${{ secrets.DROPBOX_APP_KEY}}
        DROPBOX_APP_SECRET : ${{ secrets.DROPBOX_APP_SECRET}}
        
      run: |
        python .github/workflows/fetch_dropbox.py

    # Step 5: Commit and Push Changes
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Check for changes
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Changes detected, committing and pushing..."
          git add data
          git commit -m "Downloaded files from Dropbox"
          git push
        else
          echo "No changes detected, skipping commit and push."
        fi


    - name: Save First-Depth Folders to JSON
      run: |
          python -c "
            import os, json
            
            # List only first-depth folders in 'data/' directory
            data_path = 'data'
            first_depth_folders = [name for name in os.listdir(data_path) if os.path.isdir(os.path.join(data_path, name))]
            
            # Save to JSON file
            with open('first_depth_folders.json', 'w') as f:
                json.dump(first_depth_folders, f, indent=4)
            
            print('First-depth folders saved to first_depth_folders.json:', first_depth_folders)
          "
  
      # Step 7: Commit and Push Directory JSON (if changes)
    - name: Commit and Push Directory JSON
      run: |
          git add first_depth_folders.json
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Added first-depth folders JSON"
            git push
          else
            echo "No changes detected in first-depth folder JSON."

        
