name: Fetch Files from Dropbox

on:
  workflow_dispatch:
    # This allows manual triggering of the workflow.

jobs:
  fetch-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment (to use Dropbox API)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install Dependencies
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dropbox

    # Step 4: Fetch Files from Dropbox
    - name: Fetch Files from Dropbox
      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      run: |
        python <<EOF
        import dropbox
        import os

        # Initialize Dropbox Client
        dbx = dropbox.Dropbox(os.environ['DROPBOX_ACCESS_TOKEN'])

        folder_path = ""  # Replace with the folder you want to list

        try:
            print(f"Listing files in folder: {folder_path}")
            response = dbx.files_list_folder(path=folder_path)
        
            # Iterate through the entries in the folder
            for entry in response.entries:
                if isinstance(entry, dropbox.files.FileMetadata):
                    print(f"File: {entry.name}")
                elif isinstance(entry, dropbox.files.FolderMetadata):
                    print(f"Folder: {entry.name}")
        
            # Check for more files in paginated results
            while response.has_more:
                response = dbx.files_list_folder_continue(response.cursor)
                for entry in response.entries:
                    if isinstance(entry, dropbox.files.FileMetadata):
                        print(f"File: {entry.name}")
                    elif isinstance(entry, dropbox.files.FolderMetadata):
                        print(f"Folder: {entry.name}")
        
        except dropbox.exceptions.ApiError as e:
            print(f"Dropbox API error: {e}")
        EOF

    # Step 5: Add and Commit Changes
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add files from Dropbox"
        git push
