name: Fetch strava

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  download-files:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    
    # Step 3: Install Dependencies
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
  
    # Step 4: Download Files from Dropbox
    - name: Fetch Activities
      env:
        STRAVA_CLIENT_ID : ${{ secrets.STRAVA_CLIENT_ID}}
        STRAVA_CLIENT_SECRET : ${{ secrets.STRAVA_CLIENT_SECRET}}
        STRAVA_REFRESH_TOKEN : ${{ secrets.STRAVA_REFRESH_TOKEN}}
        
      run: |
        python .github/workflows/fetch_strava.py
